-- 뉴스피드 시퀀스 (profinder.sql에서 이미 생성됨)
DROP SEQUENCE NEWSFEED_SEQ;
CREATE SEQUENCE NEWSFEED_SEQ;

-- 뉴스피드댓글 시퀀스 (profinder.sql에서 이미 생성됨)
DROP SEQUENCE NEWS_COMMENT_SEQ;
CREATE SEQUENCE NEWS_COMMENT_SEQ;

-- 1:1문의 시퀀스 (profinder.sql에서 이미 생성됨)
DROP SEQUENCE CLAIM_SEQ;
CREATE SEQUENCE CLAIM_SEQ;

-- 유,무료 컨텐츠 시퀀스 (profinder.sql에서 이미 생성됨)
DROP SEQUENCE CONTENTS_SEQ;
CREATE SEQUENCE CONTENTS_SEQ;

-- 분야 INSERT (주석처리한부분 profinder.sql에서 이미 생성됨)
SELECT * FROM CATEGORY;
--INSERT INTO CATEGORY VALUES(1,'국어');
--INSERT INTO CATEGORY VALUES(2,'영어');
--INSERT INTO CATEGORY VALUES(3,'수학');
--INSERT INTO CATEGORY VALUES(4,'과학');
--INSERT INTO CATEGORY VALUES(5,'사회');

--프로멤버 임시등록 (주석처리한부분 PROFINDER.SQL에서 이미 생성됨)
-- INSERT INTO PROMEMBERS(P_EMAIL, P_PW, P_NAME,P_NICKNAME, P_TEL1, P_TEL2, P_TEL3, P_AREA, CATE_NUM) VALUES('hope1821@naver.com', '1234', '문세운', '매미', '010', '9505', '2118','서울', 2);
SELECT * FROM PROMEMBERS;
COMMIT;

-- 뉴스피드 등록 ID=newsfeedInsert (주석처리한부분 PROFINDER.SQL에서 이미 생성됨)
--INSERT INTO NEWSFEED 
--    VALUES('NEWSFEED'||NEWSFEED_SEQ.NEXTVAL,'aa@aa','제목','내용',SYSDATE,0,0,'127.0.0.1',2);
--INSERT INTO NEWSFEED 
--    VALUES('NEWSFEED'||NEWSFEED_SEQ.NEXTVAL,'aa@aa','제목2','내용2',SYSDATE,0,0,'127.0.0.1',2);
SELECT * FROM NEWSFEED;

-- 뉴스피드 메인 ID=newsfeedMain
SELECT * FROM (SELECT ROWNUM R,A.* FROM
    (SELECT N.*,P_NICKNAME FROM NEWSFEED N,PROMEMBERS P
        WHERE N.P_EMAIL=P.P_EMAIL AND N_DEL = 0 ORDER BY N_DATE DESC)A)
            WHERE R BETWEEN 1 AND 5;

-- 뉴스피드 ajax ID=newsfeedAjax
SELECT * FROM (SELECT ROWNUM R,A.* FROM
    (SELECT N.*,P_NICKNAME FROM NEWSFEED N,PROMEMBERS P
        WHERE N.P_EMAIL=P.P_EMAIL AND N_DEL = 0 ORDER BY N_DATE DESC)A)
            WHERE R=2;

-- 분류 셀릭트 ID=categorySelect
SELECT * FROM CATEGORY ORDER BY CATE_NUM;

-- 뉴스피드댓글 불러오기 ID=newsCommentSelect
SELECT * FROM NEWS_COMMENT 
    WHERE NC_DEL=0 AND N_NUM = 'NEWSFEED2' ORDER BY NC_DATE;

-- 뉴스피드댓글 등록 ID=newsCommentInsert(주석처리한부분 PROFINDER.SQL에서 이미 생성됨)
--INSERT INTO NEWS_COMMENT 
--    VALUES('NEWS_COMMENT'||NEWS_COMMENT_SEQ.NEXTVAL,'NEWSFEED2','의적','첫댓글',SYSDATE,0,'127.0.0.1');
COMMIT;
SELECT * FROM NEWS_COMMENT;

-- 1:1문의등록 ID=claimInsert(주석처리한부분 PROFINDER.SQL에서 이미 생성됨)
--INSERT INTO CLAIM 
--    VALUES('CLAIM'||CLAIM_SEQ.NEXTVAL,'hope1821@naver.com','답장하라는문의3',SYSDATE,'기타',0);
--INSERT INTO CLAIM 
--    VALUES('CLAIM'||CLAIM_SEQ.NEXTVAL,'aa@aa','답장하라는문의4',SYSDATE,'기타',0);
SELECT * FROM CLAIM;
COMMIT;

-- 1:1문의 보기 ID=claimList
SELECT * FROM CLAIM WHERE CL_EMAIL='aa@aa' ORDER BY CL_DATE DESC;

-- 1:1문의 관리자가 보기 ID=claimAdminList
SELECT * FROM CLAIM WHERE CL_STATUS=0 ORDER BY CL_DATE;

-- 1:1문의 답변하고 처리완료로 바꾸기 ID=claimAnswerComplete
UPDATE CLAIM SET CL_STATUS = 1 WHERE CL_NUM = 'CLAIM1';

-- 유,무료 컨텐츠 등록 ID=contentInsert (주석처리한부분 PROFINDER.SQL에서 이미 생성됨)
--INSERT INTO CONTENTS 
--    VALUES('CONTENTS'||CONTENTS_SEQ.NEXTVAL,'hope1821@naver.com','제목','내용',null,null,null,0,SYSDATE,2,0,0);
SELECT * FROM CONTENTS;
COMMIT;

-- 유,무료 컨텐츠 목록 ID=contentsList
SELECT * FROM CONTENTS ORDER BY CON_DATE;