/* 관리자 */
DROP TABLE ADMIN 
   CASCADE CONSTRAINTS;

/* 분야 */
DROP TABLE CATEGORY 
   CASCADE CONSTRAINTS;

/* 파인더멤버 */
DROP TABLE FINDERMEMBERS 
   CASCADE CONSTRAINTS;
    
/* 프로멤버 */
DROP TABLE PROMEMBERS 
   CASCADE CONSTRAINTS;
    
/* 뉴스피드 */
DROP TABLE NEWSFEED 
   CASCADE CONSTRAINTS;
    
/* 뉴스피드댓글 */
DROP TABLE NEWS_COMMENT 
   CASCADE CONSTRAINTS;
    
/* 찜하기 */
DROP TABLE FAVORITE 
   CASCADE CONSTRAINTS;
    
/* 방문자목록 */
DROP TABLE VISITED 
   CASCADE CONSTRAINTS;

/* 유·무료컨텐츠 */
DROP TABLE CONTENTS 
   CASCADE CONSTRAINTS;

/* 유료질문방 */
DROP TABLE QUESTION 
   CASCADE CONSTRAINTS;
    
/* 유료질문방답변 */
DROP TABLE QANSWER 
   CASCADE CONSTRAINTS;
    
/* 퀴즈 */
DROP TABLE QUIZ 
   CASCADE CONSTRAINTS;

/* 구매내역 */
DROP TABLE BUY 
   CASCADE CONSTRAINTS;

/* 프로멤버 페이지 */
DROP TABLE PPAGE 
   CASCADE CONSTRAINTS;

/* 후기 */
DROP TABLE REVIEW 
   CASCADE CONSTRAINTS;
    
/* 자유게시판 */
DROP TABLE FBOARD 
   CASCADE CONSTRAINTS;

/* 자유게시판댓글 */
DROP TABLE FB_COMMENT 
   CASCADE CONSTRAINTS;

/* 1:1문의 */
DROP TABLE CLAIM 
   CASCADE CONSTRAINTS;

/* 자주묻는질문분류 */
DROP TABLE FAQ_CATE 
   CASCADE CONSTRAINTS;

/* 자주묻는질문 */
DROP TABLE FAQ 
   CASCADE CONSTRAINTS;

/* 좋아요 */
DROP TABLE LIKES
   CASCADE CONSTRAINTS;

/* 신고 */
DROP TABLE REPORT 
   CASCADE CONSTRAINTS;

/* 알람 */
DROP TABLE ALARM 
   CASCADE CONSTRAINTS;
    
/* 관리자 */
CREATE TABLE ADMIN (
   AD_ID VARCHAR2(100) NOT NULL, /* 아이디 */
   AD_PW VARCHAR2(100) NOT NULL, /* 비밀번호 */
   AD_NAME VARCHAR2(100) NOT NULL,/* 이름 */
    PRIMARY KEY(AD_ID)
);
select*from admin;
INSERT INTO ADMIN VALUES('sinmk','pw','신민경');
SELECT * FROM ADMIN WHERE AD_ID='sinmk';
COMMIT;
/* 분야 */
CREATE TABLE CATEGORY (
   CATE_NUM NUMBER NOT NULL, /* 분야번호 */
   CATE_NAME VARCHAR2(100) NOT NULL, /* 분야이름 */
    PRIMARY KEY(CATE_NUM)
);

-- 분야 INSERT문
UPDATE CATEGORY SET CATE_NAME='교육' WHERE CATE_NUM=1;
UPDATE CATEGORY SET CATE_NAME='비즈니스' WHERE CATE_NUM=2;
UPDATE CATEGORY SET CATE_NAME='생활과학' WHERE CATE_NUM=3;
UPDATE CATEGORY SET CATE_NAME='디자인' WHERE CATE_NUM=4;
UPDATE CATEGORY SET CATE_NAME='개발' WHERE CATE_NUM=5;
INSERT INTO CATEGORY VALUES(6,'건강/미용');
INSERT INTO CATEGORY VALUES(7,'이벤트');
INSERT INTO CATEGORY VALUES(8,'기타');

SELECT * FROM CATEGORY;
commit;
select*from promembers;

/*하위분야*/
CREATE TABLE SUB_CATE(
  SUB_CATENUM NUMBER NOT NULL,
  SUB_CATENAME VARCHAR2(100) NOT NULL,
  CATE_NUM NUMBER REFERENCES CATEGORY(CATE_NUM)
);

INSERT INTO SUB_CATE VALUES(1,'국어',1);
INSERT INTO SUB_CATE VALUES(2,'수학',1);
INSERT INTO SUB_CATE VALUES(3,'영어',1);
INSERT INTO SUB_CATE VALUES(4,'사회과학',1);
INSERT INTO SUB_CATE VALUES(5,'자연과학',1);
INSERT INTO SUB_CATE VALUES(1,'통/번역',2);
INSERT INTO SUB_CATE VALUES(2,'마케팅',2);
INSERT INTO SUB_CATE VALUES(3,'컨설팅',2);
INSERT INTO SUB_CATE VALUES(1,'요리',3);
INSERT INTO SUB_CATE VALUES(2,'인테리어',3);
INSERT INTO SUB_CATE VALUES(3,'패션DIY',3);
INSERT INTO SUB_CATE VALUES(4,'화장품/비누DIY',3);
INSERT INTO SUB_CATE VALUES(5,'셀프수리',3);
INSERT INTO SUB_CATE VALUES(1,'웹/앱디자인',4);
INSERT INTO SUB_CATE VALUES(2,'패션디자인',4);
INSERT INTO SUB_CATE VALUES(3,'제품디자인',4);
INSERT INTO SUB_CATE VALUES(4,'출판디자인',4);
INSERT INTO SUB_CATE VALUES(5,'게임그래픽디자인',4);
INSERT INTO SUB_CATE VALUES(1,'웹/앱개발',5);
INSERT INTO SUB_CATE VALUES(2,'게임개발',5);
INSERT INTO SUB_CATE VALUES(3,'SW개발',5);
INSERT INTO SUB_CATE VALUES(1,'다이어트',6);
INSERT INTO SUB_CATE VALUES(2,'헬스/트레이닝',6);
INSERT INTO SUB_CATE VALUES(3,'스킨케어',6);
INSERT INTO SUB_CATE VALUES(4,'메이크업',6);
INSERT INTO SUB_CATE VALUES(1,'촬영/영상제작',7);
INSERT INTO SUB_CATE VALUES(2,'공연',7);

SELECT*FROM SUB_CATE;
COMMIT;

/* 파인더멤버 */
CREATE TABLE FINDERMEMBERS (
    F_EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
    F_PW VARCHAR2(100) NOT NULL, /* 비밀번호 */
    F_NAME VARCHAR2(100) NOT NULL, /* 이름 */
    F_NICKNAME VARCHAR2(100) NOT NULL, /* 닉네임 */
    F_TEL1 VARCHAR2(100) NOT NULL, /* 연락처1 */
    F_TEL2 VARCHAR2(100) NOT NULL, /* 연락처2 */
    F_TEL3 VARCHAR2(100) NOT NULL, /* 연락처3 */
    F_ACCOUNTNUM VARCHAR2(100), /* 계좌번호 */
    F_BANK VARCHAR2(100), /* 계좌은행 */
    F_AREA VARCHAR2(100) NOT NULL, /* 거주지역 */
    F_POINT NUMBER(10) DEFAULT 0, /* 포인트 */
    F_PHOTO1 VARCHAR2(100) DEFAULT 'NOIMG.PNG', /* 프로필사진 */
    F_DROP NUMBER(1) DEFAULT 0, /* 탈퇴여부 */
    F_SUSPEND NUMBER(1) DEFAULT 0, /* 정지여부 */
    F_DATE DATE DEFAULT SYSDATE, /* 가입일 */
    F_MESSAGE VARCHAR2(100), /* 알림말 */
    F_PHOTO2 VARCHAR2(100), /* 추가이미지 */
    PRIMARY KEY(F_EMAIL)
);

-- 파인더멤버 INSERT문
INSERT INTO FINDERMEMBERS (F_EMAIL, F_PW, F_NAME, F_NICKNAME, F_TEL1, F_TEL2, F_TEL3, F_ACCOUNTNUM, F_BANK, F_AREA, F_PHOTO1,F_MESSAGE, F_PHOTO2)
    VALUES('hyun1330@naver.com', '11', '정성훈', '정성훈', '010', '3976', '2237', '302-0778-5449-11', '농협', '서울', '사진1', '메세지', '사진2');
INSERT INTO FINDERMEMBERS (F_EMAIL, F_PW, F_NAME, F_NICKNAME, F_TEL1, F_TEL2, F_TEL3, F_AREA)
    VALUES('finder@naver.com', '1', 'findername1', 'findernickname1', '010', '9999', '9999', '경기');
INSERT INTO FINDERMEMBERS (F_EMAIL, F_PW, F_NAME, F_NICKNAME, F_TEL1, F_TEL2, F_TEL3, F_AREA)
    VALUES('finder2@naver.com', '2', 'findername2', 'findernickname2', '010', '9998', '9999', '부산');
INSERT INTO FINDERMEMBERS (F_EMAIL, F_PW, F_NAME, F_NICKNAME, F_TEL1, F_TEL2, F_TEL3, F_AREA)
    VALUES('finder12@finder.com', '12', 'findername12', 'findernickname12', '010', '9998', '9999', '부산');
SELECT*FROM FINDERMEMBERS;
INSERT INTO FINDERMEMBERS VALUES('finder0@finder.com', 'pw', 'finder0', 'finder0', '010','1234','1234', null, null, '서울', default, default, default, default, default, null, null);
SELECT*FROM FINDERMEMBERS WHERE F_EMAIL='finder1@finder.com';
UPDATE FINDERMEMBERS SET F_POINT=F_POINT+1000 WHERE F_EMAIL='finder1@finder.com';
commit;
/* 프로멤버 */
CREATE TABLE PROMEMBERS (
    P_EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
    P_PW VARCHAR2(100) NOT NULL, /* 비밀번호 */
    P_NAME VARCHAR2(100) NOT NULL, /* 이름 */
    P_NICKNAME VARCHAR2(100) NOT NULL, /* 닉네임 */
    P_TEL1 VARCHAR2(100) NOT NULL, /* 연락처1 */
    P_TEL2 VARCHAR2(100) NOT NULL, /* 연락처2 */
    P_TEL3 VARCHAR2(100) NOT NULL, /* 연락처3 */
    P_ACCOUNTNUM VARCHAR2(100), /* 계좌번호 */
    P_BANK VARCHAR2(100), /* 계좌은행 */
    P_AREA VARCHAR2(100) NOT NULL, /* 거주지역 */
    P_POINT NUMBER(10) DEFAULT 0, /* 포인트 */
    P_PHOTO1 VARCHAR2(100) DEFAULT 'noimg.png', /* 프로필사진 */
    P_DROP NUMBER(1) DEFAULT 0, /* 탈퇴여부 */
    P_SUSPEND NUMBER(1) DEFAULT 0, /* 정지여부 */
    P_DATE DATE DEFAULT SYSDATE, /* 가입일 */
    P_MESSAGE VARCHAR2(100), /* 알림말 */
    P_PHOTO2 VARCHAR2(100), /* 추가이미지1 */
    CATE_NUM NUMBER NOT NULL, /* 분야번호 */
    PRIMARY KEY(P_EMAIL),
    FOREIGN KEY(CATE_NUM) REFERENCES CATEGORY(CATE_NUM)
);
SELECT*FROM PROMEMBERS;
COMMIT;
UPDATE PROMEMBERS SET P_POINT=20000 WHERE P_EMAIL='sinmk89@naver.com';
SELECT*FROM FINDERMEMBERS;
-- 프로멤버 INSERT문
INSERT INTO PROMEMBERS VALUES('sinmk89@naver.com','pw','신민경','밤하늘','010','8697','6064','1002-831-431-648','우리은행','서울', default, default, default, default, default, '안녕하세요.', 'bgsample.png', 3);
INSERT INTO PROMEMBERS(P_EMAIL, P_PW, P_NAME,P_NICKNAME, P_TEL1, P_TEL2, P_TEL3, P_ACCOUNTNUM, P_BANK, P_AREA,P_PHOTO1, P_MESSAGE, P_PHOTO2, CATE_NUM)
    VALUES('hyun1330@naver.com', '22', '정성훈', '정성훈', '010', '3976', '2237', '302-0778-5449-11', '농협', '서울', '사진1','메세지','사진2', 1);
INSERT INTO PROMEMBERS(P_EMAIL, P_PW, P_NAME,P_NICKNAME, P_TEL1, P_TEL2, P_TEL3, P_AREA, CATE_NUM)
    VALUES('hope1821@naver.com', '1234', '문세운', '매미', '010', '9505', '2118','서울', 2);
INSERT INTO PROMEMBERS(P_EMAIL, P_PW, P_NAME,P_NICKNAME, P_TEL1, P_TEL2, P_TEL3, P_AREA, CATE_NUM)
    VALUES('aa@aa', '1234', '에이', '에이별명', '010', '9405', '2117','서울', 2);
INSERT INTO PROMEMBERS(P_EMAIL, P_PW, P_NAME,P_NICKNAME, P_TEL1, P_TEL2, P_TEL3, P_AREA, CATE_NUM)
    VALUES('pro@naver.com', '1', 'proname1', 'pronickname1', '010', '1111', '1111', '인천', 4);
INSERT INTO PROMEMBERS(P_EMAIL, P_PW, P_NAME,P_NICKNAME, P_TEL1, P_TEL2, P_TEL3, P_AREA, CATE_NUM)
    VALUES('pro2@naver.com', '1', 'proname2', 'pronickname2', '010', '1112', '1111', '서울', 5);
INSERT INTO PROMEMBERS(P_EMAIL, P_PW, P_NAME,P_NICKNAME, P_TEL1, P_TEL2, P_TEL3, P_AREA, CATE_NUM)
    VALUES('pro3@pro.com', '3', 'proname3', 'pronickname3', '010', '1112', '1111', '서울', 5);
INSERT INTO PROMEMBERS(P_EMAIL, P_PW, P_NAME,P_NICKNAME, P_TEL1, P_TEL2, P_TEL3, P_AREA, CATE_NUM)
    VALUES('pro3@pro.com', '11', 'proname4', 'pronickname11', '010', '1112', '1111', '서울', 5);
ROLLBACK;
INSERT INTO PROMEMBERS VALUES('aa@pro.com','pw','Aplus','Aplus','010','1111','1111',null,null,'서울',default, default, default, default,default, null, null, 1);
SELECT*FROM PROMEMBERS;
SELECT*FROM FINDERMEMBERS;
/* 뉴스피드 */
CREATE TABLE NEWSFEED (
	N_NUM VARCHAR2(100) NOT NULL, /* 글번호 */
	P_EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
	N_TITLE VARCHAR2(100) NOT NULL, /* 글제목 */
	N_CONTENT CLOB NOT NULL, /* 글내용 */
	N_DATE DATE NOT NULL, /* 작성일 */
	N_HIT NUMBER NOT NULL, /* 조회수 */
	N_DEL NUMBER(1) NOT NULL, /* 삭제여부 */
	N_IP VARCHAR(100) NOT NULL, /* IP */
	CATE_NUM NUMBER NOT NULL, /* 분야번호 */
    PRIMARY KEY(N_NUM),
    FOREIGN KEY(P_EMAIL) REFERENCES PROMEMBERS(P_EMAIL),
    FOREIGN KEY(CATE_NUM) REFERENCES CATEGORY(CATE_NUM)
);

-- 뉴스피드 시퀀스 
DROP SEQUENCE NEWSFEED_SEQ;
CREATE SEQUENCE NEWSFEED_SEQ;

-- 뉴스피드 INSERT문
INSERT INTO NEWSFEED 
    VALUES('NEWSFEED'||NEWSFEED_SEQ.NEXTVAL,'aa@aa','제목','내용',SYSDATE,0,0,'127.0.0.1',2);
INSERT INTO NEWSFEED 
    VALUES('NEWSFEED'||NEWSFEED_SEQ.NEXTVAL,'aa@aa','제목2','내용2',SYSDATE,0,0,'127.0.0.1',2);

/* 뉴스피드댓글 */
CREATE TABLE NEWS_COMMENT (
    NC_NUM VARCHAR2(100) NOT NULL, /* 댓글번호 */
    N_NUM VARCHAR2(100) NOT NULL, /* 글번호 */
    NC_NAME VARCHAR2(100) NOT NULL, /* 작성자 */
    NC_CONTENT CLOB NOT NULL, /* 댓글내용 */
    NC_DATE DATE DEFAULT SYSDATE, /* 작성일 */
    NC_DEL NUMBER(1) DEFAULT 0, /* 삭제여부 */
    NC_IP VARCHAR(100) NOT NULL, /* IP */
    PRIMARY KEY(NC_NUM),
    FOREIGN KEY(N_NUM) REFERENCES NEWSFEED(N_NUM)
);

-- 뉴스피드댓글 시퀀스
DROP SEQUENCE NEWS_COMMENT_SEQ;
CREATE SEQUENCE NEWS_COMMENT_SEQ;

-- 뉴스피드댓글 INSERT문
INSERT INTO NEWS_COMMENT 
    VALUES('NEWS_COMMENT'||NEWS_COMMENT_SEQ.NEXTVAL,'NEWSFEED2','의적','첫댓글',SYSDATE,0,'127.0.0.1');

/* 찜하기 */ 
DROP TABLE FAVORITE;
CREATE TABLE FAVORITE (
    F_EMAIL VARCHAR2(100), /* 찜한사람 */
    P_EMAIL VARCHAR2(100), /* 찜당한사람 */
    FOREIGN KEY(F_EMAIL) REFERENCES FINDERMEMBERS(F_EMAIL),
    FOREIGN KEY(P_EMAIL) REFERENCES PROMEMBERS(P_EMAIL),
    CONSTRAINT FAVORITE PRIMARY KEY(F_EMAIL, P_EMAIL)
);
SELECT*FROM FAVORITE;
SELECT*FROM PROMEMBERS;
SELECT*FROM PROMEMBERS WHERE P_EMAIL='pro8@pro.com';
SELECT*FROM FINDERMEMBERS;
INSERT INTO FAVORITE VALUES('finder0@finder.com', 'aa@aa');
DELETE FROM FAVORITE WHERE P_EMAIL='pro1@pro.com';
commit;
SELECT * FROM(SELECT ROWNUM R, A.* FROM
    		(SELECT P.P_EMAIL , COUNT(P.P_EMAIL) CNT FROM FAVORITE F, PROMEMBERS P  WHERE F.P_EMAIL=P.P_EMAIL AND CATE_NUM=1 GROUP BY P.P_EMAIL
                ORDER BY CNT DESC)A)
            		WHERE R BETWEEN 1 AND 100;
                    
CREATE OR REPLACE VIEW JJIM AS
SELECT * FROM(SELECT ROWNUM R, A.* FROM
    		(SELECT P_EMAIL , COUNT(P_EMAIL) CNT FROM FAVORITE GROUP BY P_EMAIL 
                ORDER BY CNT DESC)A)
            		WHERE R BETWEEN 1 AND 6;
SELECT J.*, P.CATE_NUM, CATE_NAME FROM JJIM J, PROMEMBERS P, CATEGORY C WHERE J.P_EMAIL=P.P_EMAIL AND P.CATE_NUM=C.CATE_NUM;
commit;
SELECT * FROM(SELECT ROWNUM R,A.* FROM
    		(SELECT L_NUM,COUNT(L_NUM) CNT FROM LIKES WHERE L_NUM LIKE 'NEWSFEED%'
        		GROUP BY L_NUM ORDER BY CNT DESC)A)
            		WHERE R BETWEEN 1 AND 3;
SELECT * FROM PROMEMBERS WHERE p_email= 'pro@naver.com';
/* 방문자목록 */
CREATE TABLE VISITED (
    P_EMAIL VARCHAR2(100) NOT NULL, /* 주인 */
    V_VISITOR VARCHAR2(100) NOT NULL, /* 방문자 */
    V_DATE DATE DEFAULT SYSDATE, /* 방문시각 */
    FOREIGN KEY(P_EMAIL) REFERENCES PROMEMBERS(P_EMAIL)
);

/* 유·무료컨텐츠 */
CREATE TABLE CONTENTS (
    CON_NUM VARCHAR2(100) NOT NULL, /* 컨텐츠번호 */
    P_EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
    CON_TITLE VARCHAR2(300) NOT NULL, /* 컨텐츠제목 */
    CON_CONTENT CLOB NOT NULL, /* 컨텐츠내용 */
    CON_FILE1 VARCHAR2(100), /* 첨부파일1 */
    CON_FILE2 VARCHAR2(100), /* 첨부파일2 */
    CON_FILE3 VARCHAR2(100), /* 첨부파일3 */
    CON_PRICE NUMBER(10) NOT NULL, /* 가격 */
    CON_DATE DATE DEFAULT SYSDATE, /* 작성일 */
    CATE_NUM NUMBER NOT NULL, /* 분야번호 */
    CON_DOWNLOAD NUMBER NOT NULL, /* 다운로드수 */
    CON_DEL NUMBER(1) DEFAULT 0, /* 삭제여부 */
    PRIMARY KEY(CON_NUM),
    FOREIGN KEY(P_EMAIL) REFERENCES PROMEMBERS(P_EMAIL),
    FOREIGN KEY(CATE_NUM) REFERENCES CATEGORY(CATE_NUM)
);
SELECT * FROM(SELECT ROWNUM R, A.* FROM
    		(SELECT * FROM CONTENTS  WHERE CATE_NUM=1
                ORDER BY CON_DOWNLOAD DESC)A)
            		WHERE R BETWEEN 1 AND 6;

SELECT * FROM (
    SELECT ROWNUM R, A.* FROM (
     SELECT*FROM CONTENTS WHERE CATE_NUM=3 AND (CON_TITLE LIKE '%붉은빛%' OR CON_CONTENT LIKE '%붉은빛%') ORDER BY CON_DATE DESC)A) 
        WHERE R BETWEEN 1 AND 5;
 SELECT COUNT(*) FROM CONTENTS WHERE CON_TITLE LIKE '%붉은빛%' OR CON_CONTENT LIKE '%붉은빛%';
 SELECT * FROM (
    SELECT ROWNUM R, A.* FROM (
     SELECT*FROM CONTENTS WHERE CATE_NUM=2 AND (CON_TITLE LIKE '%Contents%' OR CON_CONTENT LIKE '%Contents%') ORDER BY CON_DATE DESC)A) 
        WHERE R BETWEEN 11 AND 15;
-- 유·무료컨텐츠 시퀀스
DROP SEQUENCE CONTENTS_SEQ;
CREATE SEQUENCE CONTENTS_SEQ;

-- 유·무료컨텐츠 INSERT문
INSERT INTO CONTENTS 
    VALUES('CONTENTS'||CONTENTS_SEQ.NEXTVAL,'hope1821@naver.com','제목','내용',null,null,null,0,SYSDATE,2,0,0);
INSERT INTO CONTENTS 
    VALUES('CONTENTS'||CONTENTS_SEQ.NEXTVAL,'haenemm@naver.com','붉은빛 자태를 뽐내며 싱그러운 매력을 자랑하는 딸기. 그 어떤 과일보다 상큼하고 달콤한 맛을 자랑하는 딸기가 맛의 절정에 오르면서 카페 브랜드마다 딸기를 테마로 한 신메뉴를 앞다투어 출시하고 있다. ',
    '가장 먼저 딸기를 활용한 디저트 메뉴를 선보인 설빙 매번 기발한 아이디어가 돋보이는 디저트로 소비자들을 사로잡은 설빙은 이번에도 역시 독특한 디저트를 선보여 화제를 모았다. 신메뉴인 레드벨벳 딸기설빙은 케이크를 닮은 비주얼로 딸기 설빙 겉면은 폭신한 레드벨벳 케이크로 감쌌다. 출시되자마자 가장 많이 팔린 생딸기 시리즈 메뉴로 등극하며 꾸준한 인기를 얻고 있다. 아울러 함께 출시한 생딸기 초코브레드는 따뜻한 허니버터 브레드 위에 달콤한 생딸기와 생크림 그리고 초코 소스를 따로 제공해 뿌려먹는 신개념 허니브레드 메뉴다
     활용한 디저트 메뉴를 선보인 설빙 매번 기발한 아이디어가 돋보이는 디저트로 소비자들을 사로잡은 설빙은 이번에도 역시 독특한 디저트를 선보여 화제를 모았다. 신메뉴인 레드벨벳 딸기설빙은 케이크를 닮은 비주얼로 딸기 설빙 겉면은 폭신한 레드벨벳 케이크로 감쌌다. 출시되자마자 가장 많이 팔린 생딸기 시리즈 메뉴로 등극하며 꾸준한 인기를 얻고 있다. 아울러 함께 출시한 생딸기 초코브레드는 따뜻한 허니버터 브레드 위에 달콤한 생딸기와 생크림 그리고 초코 소스를 따로 제공해 뿌려먹는 신개념 허니브레드 메뉴다
    가장 먼저 딸기를 활용한 디저트 메뉴를 선보인 설빙 매번 기발한 아이디어가 돋보이는 디저트로 소비자들을 사로잡은 설빙은 이번에도 역시 독특한 디저트를 선보여 화제를 모았다. 신메뉴인 레드벨벳 딸기설빙은 케이크를 닮은 비주얼로 딸기 설빙 겉면은 폭신한 레드벨벳 케이크로 감쌌다. 출시되자마자 가장 많이 팔린 생딸기 시리즈 메뉴로 등극하며 꾸준한 인기를 얻고 있다. 아울러 함께 출시한 생딸기 초코브레드는 따뜻한 허니버터 브레드 위에 달콤한 생딸기와 생크림 그리고 초코 소스를 따로 제공해 뿌려먹는 신개념 허니브레드 메뉴다
    가장 먼저 딸기를 활용한 디저트 메뉴를 선보인 설빙 매번 기발한 아이디어가 돋보이는 디저트로 소비자들을 사로잡은 설빙은 이번에도 역시 독특한 디저트를 선보여 화제를 모았다. 신메뉴인 레드벨벳 딸기설빙은 케이크를 닮은 비주얼로 딸기 설빙 겉면은 폭신한 레드벨벳 케이크로 감쌌다. 출시되자마자 가장 많이 팔린 생딸기 시리즈 메뉴로 등극하며 꾸준한 인기를 얻고 있다. 아울러 함께 출시한 생딸기 초코브레드는 따뜻한 허니버터 브레드 위에 달콤한 생딸기와 생크림 그리고 초코 소스를 따로 제공해 뿌려먹는 신개념 허니브레드 메뉴다
    ',null,null,null,0,SYSDATE,2,0,0);  
    commit;
    SELECT * FROM CATEGORY ORDER BY CATE_NUM;

select * from promembers;

/* 유료질문방 */
CREATE TABLE QUESTION (
    Q_NUM VARCHAR2(100) NOT NULL, /* 질문번호 */
    P_EMAIL VARCHAR2(100) NOT NULL, /* 희망답변자 */
    F_EMAIL VARCHAR2(100) NOT NULL, /* 질문자 */
    CATE_NUM NUMBER NOT NULL, /* 분야번호 */
    Q_TITLE VARCHAR2(300) NOT NULL, /* 질문제목 */
    Q_CONTENT CLOB NOT NULL, /* 질문내용 */
    Q_DATE DATE DEFAULT SYSDATE, /* 작성일 */
    Q_PRICE NUMBER(10) NOT NULL, /* 설정가격 */
    Q_ACCEPT NUMBER(1) DEFAULT 0, /* 수락여부 */
    Q_SHOW NUMBER(1) DEFAULT 0, /* 공개여부 */
    Q_STAR NUMBER(1) DEFAULT 0, /* 별점 */
    PRIMARY KEY(Q_NUM),
    FOREIGN KEY(P_EMAIL) REFERENCES PROMEMBERS(P_EMAIL),
    FOREIGN KEY(F_EMAIL) REFERENCES FINDERMEMBERS(F_EMAIL),
    FOREIGN KEY(CATE_NUM) REFERENCES CATEGORY(CATE_NUM)
);

-- 유료질문방 시퀀스 생성
DROP SEQUENCE QUESTION_SEQ;
CREATE SEQUENCE QUESTION_SEQ;

-- 유료질문방 INSERT
INSERT INTO QUESTION (Q_NUM, P_EMAIL, F_EMAIL, CATE_NUM, Q_TITLE, Q_CONTENT, Q_PRICE, Q_SHOW, Q_STAR) 
    VALUES('QUESTION'||QUESTION_SEQ.NEXTVAL,'pro@naver.com', 'finder@naver.com', 4, '질문제목1', '질문내용1', 100, 1, 3.9);
INSERT INTO QUESTION (Q_NUM, P_EMAIL, F_EMAIL, CATE_NUM, Q_TITLE, Q_CONTENT, Q_PRICE) 
    VALUES('QUESTION'||QUESTION_SEQ.NEXTVAL,'pro2@naver.com', 'finder2@naver.com', 5, '질문제목2', '질문내용2', 200);

/* 유료질문방답변 */
CREATE TABLE QANSWER (
    Q_NUM VARCHAR2(100) NOT NULL, /* 질문번호 */
    QA_CONTENT CLOB NOT NULL, /* 답변내용 */
    QA_DATE DATE DEFAULT SYSDATE, /* 답변일 */
    PRIMARY KEY(Q_NUM),
    FOREIGN KEY(Q_NUM) REFERENCES QUESTION(Q_NUM)
);
select*from qanswer;
select*from question;
select*from likes;
-- 유료질문방답변 INSERT문
INSERT INTO QANSWER(Q_NUM, QA_CONTENT) VALUES('QUESTION1', '질문1_답변1');
INSERT INTO QANSWER(Q_NUM, QA_CONTENT) VALUES('QUESTION2', '질문2_답변1');

/* 퀴즈 */
CREATE TABLE QUIZ (
	QUIZ_NUM VARCHAR2(100) NOT NULL, /* 퀴즈번호 */
	P_EMAIL VARCHAR2(100) NOT NULL, /* 출제자 */
    CATE_NUM NUMBER NOT NULL, /* 분야번호 */
	QUIZ_GROUP VARCHAR2(100) NOT NULL, /* 퀴즈그룹 */
    QUIZ_TITLE VARCHAR2(300) NOT NULL, /* 퀴즈제목 */
	QUIZ_CONTENT CLOB NOT NULL, /* 퀴즈내용 */
	QUIZ_ANSWER VARCHAR2(100) NOT NULL, /* 퀴즈정답 */
	QUIZ_SELECT1 VARCHAR2(300) NOT NULL, /* 선택지1 */
	QUIZ_SELECT2 VARCHAR2(300) NOT NULL, /* 선택지2 */
	QUIZ_SELECT3 VARCHAR2(300) NOT NULL, /* 선택지3 */
	QUIZ_SELECT4 VARCHAR2(300) NOT NULL, /* 선택지4 */
	QUIZ_PRICE NUMBER NOT NULL, /* 가격 */
    PRIMARY KEY(QUIZ_NUM),
    FOREIGN KEY(P_EMAIL) REFERENCES PROMEMBERS(P_EMAIL),
    FOREIGN KEY(CATE_NUM) REFERENCES CATEGORY(CATE_NUM)
);

/* 구매내역 */
CREATE TABLE BUY (
    F_EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
    BUY_NUM VARCHAR2(100) NOT NULL, /* 구매상품번호 */
    BUY_DATE DATE NOT NULL,
    FOREIGN KEY(F_EMAIL) REFERENCES FINDERMEMBERS(F_EMAIL)
);

/* 프로멤버페이지 */
CREATE TABLE PPAGE (
    P_EMAIL VARCHAR2(100) NOT NULL, /* 이메일 */
    N_NUM VARCHAR2(100), /* 뉴스피드번호 */
    Q_NUM VARCHAR2(100), /* 질문번호 */
    CON_NUM VARCHAR2(100), /* 컨텐츠번호 */
    FOREIGN KEY(P_EMAIL) REFERENCES PROMEMBERS(P_EMAIL),
    FOREIGN KEY(N_NUM) REFERENCES NEWSFEED(N_NUM),
    FOREIGN KEY(Q_NUM) REFERENCES QUESTION(Q_NUM),
    FOREIGN KEY(CON_NUM) REFERENCES CONTENTS(CON_NUM)
);

/* 후기 */
CREATE TABLE REVIEW (
    RE_NUM VARCHAR2(100) NOT NULL, /* 후기번호 */
    RE_CONNUM VARCHAR2(100) NOT NULL, /* 컨텐츠번호 */
    RE_NAME VARCHAR2(100) NOT NULL, /* 작성자 */
    RE_CONTENT CLOB NOT NULL, /* 후기내용 */
    RE_DATE DATE DEFAULT SYSDATE, /* 작성일 */
    RE_STAR NUMBER(1), /* 평점 */
    PRIMARY KEY(RE_NUM)
);

/* 자유게시판 */
CREATE TABLE FBOARD (
	FB_NUM VARCHAR2(100) NOT NULL, /* 글번호 */
	FB_NAME VARCHAR2(100) NOT NULL, /* 작성자 */
	FB_TITLE VARCHAR2(300) NOT NULL, /* 글제목 */
	FB_CONTENT CLOB NOT NULL, /* 글내용 */
	FB_DATE DATE DEFAULT SYSDATE, /* 작성일 */
	FB_HIT NUMBER DEFAULT 0, /* 조회수 */
	FB_DEL NUMBER(1) DEFAULT 0, /* 삭제여부 */
	FB_IP VARCHAR2(100) NOT NULL, /* IP */
    PRIMARY KEY(FB_NUM)
);


-- 자유게시판 시퀀스
DROP SEQUENCE FBOARD_SEQ;
CREATE SEQUENCE FBOARD_SEQ;

-- 자유게시판 INSERT문
INSERT INTO FBOARD(FB_NUM, FB_NAME, FB_TITLE, FB_CONTENT, FB_IP)
    VALUES('FBOARD'||FBOARD_SEQ.NEXTVAL, '이름', '제목', '본문', '아이피');

/* 자유게시판댓글 */
CREATE TABLE FB_COMMENT (
	FC_NUM VARCHAR2(100) NOT NULL, /* 댓글번호 */
	FB_NUM VARCHAR2(100) NOT NULL, /* 글번호 */
	FC_NAME VARCHAR2(100) NOT NULL, /* 작성자 */
	FC_CONTENT CLOB NOT NULL, /* 댓글내용 */
    FC_GROUP VARCHAR2(100) NOT NULL, /* 댓글그룹 */
	FC_INDENT NUMBER(1) DEFAULT 0, /* 들여쓰기 */
	FC_REF VARCHAR2(100), /* 참조댓글 */
	FC_DATE DATE DEFAULT SYSDATE, /* 작성일 */
	FC_DEL NUMBER(1) DEFAULT 0, /* 삭제여부 */
	FC_IP VARCHAR2(100) NOT NULL, /* IP */
    PRIMARY KEY(FC_NUM),
    FOREIGN KEY(FB_NUM) REFERENCES FBOARD(FB_NUM),
    FOREIGN KEY(FC_REF) REFERENCES FB_COMMENT(FC_NUM)
);

-- 자유게시판댓글 시퀀스
DROP SEQUENCE FB_COMMENT_SEQ;
CREATE SEQUENCE FB_COMMENT_SEQ;

/* 1:1문의 */
CREATE TABLE CLAIM (
	CL_NUM VARCHAR2(100) NOT NULL, /* 문의번호 */
	CL_EMAIL VARCHAR2(100) NOT NULL, /* 문의자이메일 */
    CL_NICKNAME VARCHAR2(100)NOT NULL,/*문의자닉네임*/
	CL_CONTENT CLOB NOT NULL, /* 문의내용 */
	CL_DATE DATE DEFAULT SYSDATE, /* 문의시각 */
	CL_CATE VARCHAR2(100) NOT NULL, /* 문의분류 */
	CL_STATUS NUMBER(1) DEFAULT 0, /* 처리상태 */
    PRIMARY KEY(CL_NUM)
);

-- 1:1문의 시퀀스
DROP SEQUENCE CLAIM_SEQ;
CREATE SEQUENCE CLAIM_SEQ;

-- 1:1문의 INSERT문
INSERT INTO CLAIM 
    VALUES('CLAIM'||CLAIM_SEQ.NEXTVAL,'hope1821@naver.com','매미','답장하라는문의3',SYSDATE,'기타',0);
INSERT INTO CLAIM 
    VALUES('CLAIM'||CLAIM_SEQ.NEXTVAL,'aa@aa','답장하라는문의4',SYSDATE,'기타',0);
SELECT * FROM CLAIM;

/* 자주묻는질문분류 */
CREATE TABLE FAQ_CATE (
	FAQ_CATENUM NUMBER NOT NULL, /* FAQ분류번호 */
	FAQ_CATENAME VARCHAR2(100) NOT NULL, /* FAQ분류이름 */
    PRIMARY KEY(FAQ_CATENUM)
);

-- 자주묻는질문분류 INSERT문
INSERT INTO FAQ_CATE VALUES(1,'회원정보');        
INSERT INTO FAQ_CATE VALUES(2,'판매 관련');        
INSERT INTO FAQ_CATE VALUES(3,'구매관련');     


/* 자주묻는질문 */
CREATE TABLE FAQ (
	FAQ_NUM VARCHAR2(100) NOT NULL, /* FAQ번호 */
	FAQ_CATENUM NUMBER NOT NULL, /* FAQ분류번호 */
	FAQ_TITLE VARCHAR2(100) NOT NULL, /* FAQ제목 */
	FAQ_CONTENT CLOB NOT NULL, /* FAQ내용 */
    PRIMARY KEY(FAQ_NUM),
    FOREIGN KEY(FAQ_CATENUM) REFERENCES FAQ_CATE(FAQ_CATENUM)
);

-- FAQ 시퀀스
DROP SEQUENCE FAQ_SEQ;
CREATE SEQUENCE FAQ_SEQ;

-- FAQ INSERT문
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,1,'회원가입','회원가입 버튼을 찾지 못할시 Login버튼을 눌러보세요');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,1,' 비밀번호 찾기',' 비밀번호(Forgot Password?) 찾기 버튼을 눌러주세요');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,1,' 회원정보 수정','회원정보 수정 버튼을 눌러서 수정 하세요 ');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,1,' profinder에 대한 설명','저희 사이트는 pro 멤버와 finder 멤버들이 서로 의사소통하는 부분유료 커뮤니케이션 입니다. 누구나 등록이 가능 하며 
Pro Member는 자신의 능력을 원하는 가격으로 거래 하면서 자신의 이름을 알릴수있답니다.
Finder Member는 자신의 원하는 분야의 컨텐츠를 소액결제를 통해서 구입이 가능하며 필요한 부분만 적은 가격으로 구입이 가능합니다.
');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,1,'신고 안내','본 사이트에서 부적절한 컨텐츠를 발견시 신고 버튼을 통한 신고를 부탁드립니다. 이용자들의 쾌적한 이용을 위한 협조를 부탁드립니다.');

INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,2,'계좌번호 변경','계좌번호는 변경은 정보수정에 들어 가셔서 계좌번호 변경을 하시면됩니다. ');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,2,'수수료 안내 ',' PROFINDER는 판매 수수료를 10%입니다. 10%의 비용은 결제 대행 및 문자발송 서버 유지비용으로 사용 됩니다. ');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,2,'판매 안내',' 컨텐츠의 판매는 ProMember로 가입하셔야 이용이 가능하며 필수적인 조건은 아닙니다.
');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,2,'송금안내','매월 1일 오전 중 정산 등록이 진행됩니다. 정산이 완료 . 정산 받을 금액은 이전 달 말일까지 정산되지 않은 판매금액의 "실 지급 금액"의 합계가 됩니다.
정산 받으실 금액의 총 합계 5만원을 넘지 않을 경우에는 다음달로 정산됩니다. 다음 달로 이월되더라도 기존에 받았던 금액은 사라지지 않으며, 해당 금액을 포함하여 정산이 이루어집니다.
');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,3,'구매 안내','컨텐츠는 무료 컨텐츠 일부와 유료 컨텐츠로 이루어져 있으며 유료 컨텐츠는 포인트 충전이후에 이용이 가능합니다.');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,3,'직거래 안내',' PROFINDER 사이트에서는 개인간의 직거래로 문제가 발생시에는 아무런 도움을 드릴 수 없습니다.');
INSERT INTO FAQ VALUES('FAQ'||FAQ_SEQ.NEXTVAL,3,'컨텐츠 환불','본 컨텐츠는 디지털 제품으로 환불이 어려운점 양해 부탁드립니다.');

/* 좋아요 */
DROP TABLE LIKES;
CREATE TABLE LIKES (
	L_NUM VARCHAR2(100) NOT NULL, /* 인덱스 */
	L_LIKER VARCHAR2(100) NOT NULL, /* 좋아요한사람 */    
    CONSTRAINT LIKES PRIMARY KEY(L_NUM, L_LIKER)
);
SELECT*FROM FINDERMEMBERS;
SELECT*FROM QUESTION;
INSERT INTO LIKES VALUES('NEWSFEED41','ABC');
SELECT*FROM LIKES;
COMMIT;

/* 신고 */
CREATE TABLE REPORT (
	REP_NUM VARCHAR2(100) NOT NULL, /* 인덱스 */
	REP_REPORTER VARCHAR2(100) NOT NULL, /* 신고자 */
	REP_WHY CLOB NOT NULL, /* 신고사유 */
    REP_DONE NUMBER(1) DEFAULT 0
);

/* 알람 */
CREATE TABLE ALARM (
	AL_RECEIVER VARCHAR2(100) NOT NULL, /* 수신자 */
	AL_REFNUM VARCHAR2(100) NOT NULL, /* 수신자작성인덱스 */
	AL_CHECKNUM VARCHAR2(100) NOT NULL /* 확인할인덱스 */
);
    
SELECT * FROM ADMIN; /* 관리자 */
SELECT * FROM CATEGORY; /* 분야 */ 
SELECT * FROM FINDERMEMBERS; /* 파인더멤버 */
SELECT * FROM PROMEMBERS; /* 프로멤버 */
SELECT * FROM NEWSFEED; /* 뉴스피드 */
SELECT * FROM NEWS_COMMENT; /* 뉴스피드댓글 */ 
SELECT * FROM FAVORITE; /* 찜하기 */
SELECT * FROM VISITED; /* 방문자목록 */
SELECT * FROM CONTENTS; /* 유·무료컨텐츠 */
SELECT * FROM QUESTION; /* 유료질문방 */
SELECT * FROM QANSWER; /* 유료질문방답변 */
SELECT * FROM QUIZ; /* 퀴즈 */
SELECT * FROM BUY; /* 구매내역 */
SELECT * FROM PPAGE; /* 프리랜서페이지 */
SELECT * FROM REVIEW; /* 후기 */
SELECT * FROM FBOARD; /* 자유게시판 */
SELECT fb_date FROM FBOARD;

SELECT * FROM FB_COMMENT; /* 자유게시판댓글 */
SELECT * FROM CLAIM; /* 1:1문의 */
SELECT * FROM FAQ_CATE; /* 자주묻는질문분류 */
SELECT * FROM FAQ; /* 자주묻는질문 */
SELECT * FROM LIKES; /* 좋아요 */
SELECT * FROM REPORT; /* 신고 */
SELECT * FROM ALARM; /* 알람 */

SELECT * FROM CLAIM WHERE CL_STATUS=0 ORDER BY CL_DATE;
SELECT * FROM (SELECT ROWNUM R,A.* FROM
    		(SELECT N.*,P_NICKNAME FROM NEWSFEED N,PROMEMBERS P
        		WHERE N.P_EMAIL=P.P_EMAIL AND N_DEL = 0 ORDER BY N_DATE DESC)A)
            		WHERE R BETWEEN 1 AND 5;
                    
                    
SELECT *
    		FROM (SELECT ROWNUM RN, A.*
            		FROM (SELECT Q.*, P.P_NICKNAME, F.F_NICKNAME FROM QUESTION Q, PROMEMBERS P, FINDERMEMBERS F WHERE Q.P_EMAIL = P.P_EMAIL AND Q.F_EMAIL = F.F_EMAIL ORDER BY Q_DATE DESC)A)
    		WHERE RN BETWEEN 1 AND 6 AND P_EMAIL = 'hope1821@naver.com';
            
            INSERT INTO QUESTION (Q_NUM, P_EMAIL, F_EMAIL, CATE_NUM, Q_TITLE, Q_CONTENT, Q_PRICE) 
   			 VALUES('QUESTION'||QUESTION_SEQ.NEXTVAL,'hope1821@naver.com', 'hyun1330@naver.com', 1, '제목', '제목', 100);

SELECT * FROM(SELECT ROWNUM R,A.* FROM
    		(SELECT L_NUM,COUNT(L_NUM) CNT FROM LIKES WHERE L_NUM LIKE 'NEWSFEED%'
        		GROUP BY L_NUM ORDER BY CNT DESC)A)
            		WHERE R BETWEEN 1 AND 3;
SELECT * FROM (SELECT ROWNUM R,A.* FROM
    		(SELECT N.*,P_NICKNAME FROM NEWSFEED N,PROMEMBERS P
        		WHERE N.P_EMAIL=P.P_EMAIL AND N_DEL = 0 ORDER BY N_DATE DESC)A)
            		WHERE R=1;
SELECT * FROM(SELECT ROWNUM R,A.* FROM
    		(SELECT L_NUM,COUNT(L_NUM) CNT FROM LIKES WHERE L_NUM LIKE 'NEWSFEED%'
        		GROUP BY L_NUM ORDER BY CNT DESC)A)
            		WHERE R BETWEEN 1 AND 7;
SELECT N.*,P_NICKNAME FROM NEWSFEED N,PROMEMBERS P 
    		WHERE N.P_EMAIL=P.P_EMAIL AND N_NUM = 'NEWSFEED1';

--QUESTION RANKINGS FROM ALL
SELECT * FROM(SELECT ROWNUM R,A.* FROM
    		(SELECT L_NUM,COUNT(L_NUM) CNT FROM LIKES WHERE L_NUM LIKE 'QUESTION%'
        		GROUP BY L_NUM ORDER BY CNT DESC)A)
            		WHERE R BETWEEN 1 AND 6;
--QUESTION RANKINGS FROM CATE_NUM=1
SELECT * FROM(SELECT ROWNUM R,A.* FROM
    		(SELECT L_NUM,COUNT(L_NUM) CNT FROM LIKES L, QUESTION Q WHERE L_NUM LIKE 'QUESTION%' AND L_NUM=Q_NUM AND CATE_NUM=1
        		GROUP BY L_NUM ORDER BY CNT DESC)A)
            		WHERE R BETWEEN 13 AND 24;
SELECT*FROM QUESTION WHERE CATE_NUM=1;
SELECT*FROM CONTENTS;

COMMIT;
